.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. gasbit_qt test_gasbit_qt
clean: FORCE
	$(MAKE) -C .. gasbit_qt_clean test_gasbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_gasbit_qt_check
gasbit-qt gasbit-qt.exe: FORCE
	 $(MAKE) -C .. gasbit_qt
